# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: accumulator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'accumulator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61\x63\x63umulator.proto\x12\x10\x63lient_streaming\"\x17\n\x06Number\x12\r\n\x05value\x18\x01 \x01(\x05\"\x14\n\x05Total\x12\x0b\n\x03sum\x18\x01 \x01(\x05\x32K\n\x0b\x41\x63\x63umulator\x12<\n\x03Sum\x12\x18.client_streaming.Number\x1a\x17.client_streaming.Total\"\x00(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'accumulator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NUMBER']._serialized_start=39
  _globals['_NUMBER']._serialized_end=62
  _globals['_TOTAL']._serialized_start=64
  _globals['_TOTAL']._serialized_end=84
  _globals['_ACCUMULATOR']._serialized_start=86
  _globals['_ACCUMULATOR']._serialized_end=161
# @@protoc_insertion_point(module_scope)
